[package]
name = "StudyRust"
version = "0.1.0"
authors = ["zhengtiantian-easi <a1157790064@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
